# COMPSCI 589 HW1

#### Name: Haochen Wang

### SECTION 0: Load Libraries

In [490]:
import sklearn.model_selection
import scipy
import numpy as np
import csv
import math
import matplotlib.pyplot as plt
from operator import itemgetter
from collections import Counter

### SECTION 2: Evaluating Decision Tree

In [491]:
# Import Document

house_file = open('house_votes_84.csv', encoding='utf-8-sig')
csvreader = csv.reader(house_file)
houserows = []
for row in csvreader:
        houserows.append(row)

hvcat = houserows[0]
# print(housevotecat)

#housevotedat = np.array([[int(element) for element in row] for row in houserows[1:]]).T
housevotedat = np.array(houserows[1:]).astype(int).T

print(housevotedat)

[[1 1 0 ... 1 1 1]
 [2 2 2 ... 0 1 2]
 [1 1 2 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 0]
 [2 0 1 ... 2 2 1]
 [1 1 0 ... 1 1 1]]


In [492]:
house_file = open('housetest.csv', encoding='utf-8-sig')
csvreader = csv.reader(house_file)
houser = []
for row in csvreader:
        houser.append(row)

hvct = houser[0]
# print(housevotecat)

hvdt = np.array([[int(element) for element in row] for row in houser[1:]]).T

print(hvdt)

[[1 1 0 1 2 1 1]
 [2 2 2 2 2 2 2]
 [1 1 2 2 2 2 1]
 [2 2 0 1 1 1 2]
 [2 2 2 0 2 2 2]
 [2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [2 1 1 1 1 1 1]
 [0 1 2 2 2 1 1]
 [2 2 1 1 0 1 1]
 [2 2 2 2 2 2 0]
 [2 2 2 1 2 2 2]
 [1 1 1 1 2 2 2]
 [2 0 1 2 2 2 2]
 [1 1 0 0 0 0 0]]


In [493]:
# Node Class
class Treenode:
    type = ""
    label = None
    testattribute = ""
    edge = {}

    def __init__(self, label, type):
        self.label = label
        self.type = type
        # self.left = left
        # self.right = right


In [494]:
# Define helper functions that I use in decision tree.

def same(column):
    return all(item == column[0] for item in column)

def majority(column):
    return np.argmax(np.bincount(column))

def entropy(col):
    values = list(Counter(col).values())
    ent = 0
    for value in values:
        k = (value/sum(values))
        ent += -k*math.log(k,2)
    return ent

def gini(col):
    values = list(Counter(col).values())
    ginivalue = 1
    for value in values:
        prob = (value/sum(values))
        ginivalue -= prob**2
    return ginivalue

# test = np.array([1,1,3,3,11,11])
# same(test)
# majority(test)

# test1 = np.array([1,1,0,0,0]) # should get entropy .971, gini .48
# test2 = np.array([1,1,1,1,1,0,0,0,0,0,0,0,0,0]) # should get entropy .940, gini.459
# entropy(test2)

In [495]:
# Define three test criteria: 
    
# ID3 - Entropy Gain 

def id3(collist, listattribution):
    original_ent = entropy(collist[-1])
    smallest_ent = 1
    i = 0

    # bestindex = i
    best = listattribution[i]
    for attributes in listattribution[:-1]: # I keep the last column: the target/label.
        liskey = list(Counter(collist[i]).keys())
        listofcategory = []
        for value in liskey:
            index = [idx for idx, element in enumerate(collist[i]) if element == value]
            category = np.array(collist[-1][index]) 
            listofcategory.append(category) # list of nparrays of target/label/categories.

        ent = 0
        for cat in listofcategory:
            a = len(cat)/len(collist[i]) # This is probability
            ent += a * entropy(cat) # probability multiple by entropy

        if ent < smallest_ent:
            smallest_ent = ent
            best = attributes
            # bestindex = i
        i+=1

    return best, original_ent-ent

# C4.5 - Entrophy Ratio 
# CART - Gini Impurity
def cart(collist, listattribution):
    smallest_gini = 1
    i = 0
    # bestindex = i
    best = listattribution[i]
    for attributes in listattribution[:-1]: # I keep the last column: the target/label.
        liskey = list(Counter(collist[i]).keys())
        listofcategory = []
        for value in liskey:
            index = [idx for idx, element in enumerate(collist[i]) if element == value]
            category = np.array(collist[-1][index]) 
            listofcategory.append(category) # list of nparrays of target/label/categories.

        gin = 0
        for cat in listofcategory:
            a = len(cat)/len(collist[i]) # This is probability
            gin += a * gini(cat) # probability multiple by gini

        if gin < smallest_gini:
            smallest_gini = gin
            best = attributes
            # bestindex = i
        i+=1

    return best, gin
    

In [497]:
# Decision Tree
def decisiontree(dataset: np.array, listattributes: list, algortype: str ='id3'):
    def processbest(algor):
        if algor == "id3":
            return id3(datasetcopy, listattricopy)
        elif algor == "cart":
            return cart(datasetcopy, listattricopy)
        else: 
            return cart(datasetcopy, listattricopy)

    datasetcopy = np.copy(dataset)
    listattricopy = listattributes.copy()
    
    node = Treenode(label=-1,type="decision")

    if same(datasetcopy[-1]):
        node.type = "leaf"
        node.label = datasetcopy[-1][0]
        return node
    
    if len(listattricopy) == 0:
        node.type = "leaf"
        node.label = majority(datasetcopy[-1])
        return node

    bestattribute = processbest(algortype)[0]
    node.testattribute = bestattribute
    bindex = listattricopy.index(bestattribute)

    bigv = list(Counter(datasetcopy[bindex]).keys())

    subdatalists = []
    for smallv in bigv:
        index = [idx for idx, element in enumerate(datasetcopy[bindex]) if element == smallv]
        subdatav = np.array(datasetcopy.T[index]).T
        subdatav = np.delete(subdatav,bindex,0)  # I delete the column I already used using bindex as reference. 
        # Then, later, pop the same index from list attribute.
        subdatalists.append(subdatav) # list of nparrays of target/label/categories.

    listattricopy.pop(bindex)
    
    edge = {}
    sdindex = 0
    for subvdata in subdatalists:
        if subvdata.size == 0:
            node.type = "leaf"
            node.label = majority(subdatav[-1])

        subtree = decisiontree(subvdata, listattricopy, algortype)
        attributevalue = bigv[sdindex]
        edge[attributevalue] = subtree
        sdindex += 1

    node.edge = edge

    return node

In [526]:
id3(housevotedat,hvcat)
firsttree = decisiontree(housevotedat, hvcat, 'id3')
print(firsttree.edge)

{2: <__main__.Treenode object at 0x12a53aa70>, 0: <__main__.Treenode object at 0x12a53ba30>, 1: <__main__.Treenode object at 0x12a538850>}


In [499]:
t1 = np.array([[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,0],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,0],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,1],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,1],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,0]]).T
# Counter(t).keys()
ind = [1,3,3]
dex = [0,2,6,9,14,15]
t = np.array(t1.T[ind]).T
t2 = np.delete(t,3,0)
# print(t2)

thaha = np.array([[1],[2],[3]])
    
print(thaha.size)

3
